### ISSUE TITLE
API for Recent notes /api/v1/notes/recents

### ISSUE THREAD

**Issue by thakkarnetram** [thakkarnetram/BeProductiveBackend#11]
This will give the user specific recent notes can set a threshold to get recent 2-3  notes .
Also when submitting your PR Please Attach the API response you get after hitting this end point

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this, please assign

**Comment by IrfanSalim** [comment]
@thakkarnetram 

I am unable to start the server even after configuring the env.dev file, getting an error

![image](https://github.com/thakkarnetram/BeProductiveBackend/assets/109443065/68dc9587-b884-463e-bc51-0e3612c8acee)

**Comment by thakkarnetram** [comment]
create  a .env file and use docker to run

**Comment by IrfanSalim** [comment]
can you suggest how to run on gitpod?

**Comment by thakkarnetram** [comment]
![image](https://github.com/thakkarnetram/BeProductiveBackend/assets/97296994/cc8079c0-a47c-4f0e-aaf8-e4f453299f1f)
Direct open

**Comment by IrfanSalim** [comment]
I've opened the repo in gitpod, no idea how to run in docker.

**Comment by thakkarnetram** [comment]
just locally install docker first create an env file in the root directory .and run docker compose -f  < insert the file name given for development > add .yaml up

**Comment by IrfanSalim** [comment]
I tried locally as well but was unable to start the server, some issue with node not sure what, my apologies.

You can assign it to someone else.

**Comment by thakkarnetram** [comment]
@IrfanSalim You can try now. I have updated the CONTRIBUTING.md file . In order to set up the project

**Comment by savitakatwe** [comment]
Assign this to me i will work on this
@thakkarnetram

**Comment by thakkarnetram** [comment]
@savitakatwe Assigned

**Comment by savitakatwe** [comment]
@thakkarnetram I am not able to do this work kinda stuck with other work.
