### ISSUE TITLE
Refactor existing code for better readability

### ISSUE THREAD

**Issue by ujwalkumar1995** [thakkarnetram/BeProductiveBackend#15]
All the controllers are under a common controller (actionController). It should be split into different controllers for better readability. Splitting can be done on the basis of the entities (todos, notes etc.)
Similar refactoring can be done for routes.

**Comment by thakkarnetram** [comment]
@ujwalkumar1995 As I am having lack of time RN  . Currently I'm writing tests for the APIS .You wanna take it up ? I can assign you this .

**Comment by ujwalkumar1995** [comment]
Hey @thakkarnetram 
This is a basic refactoring issue. Would let people new to the repo to try and contribute to this. I can pick it up later if no one asks for the issue :)

**Comment by thakkarnetram** [comment]
@ujwalkumar1995 Okay . No worries !

**Comment by savitakatwe** [comment]
I would like to work on this you can assign it to me @ujwalkumar1995

**Comment by thakkarnetram** [comment]
@savitakatwe Done

**Comment by savitakatwe** [comment]
@thakkarnetram I am not able to do this work kinda stuck with other work.

**Comment by gurshaan17** [comment]
is this issue still open?

**Comment by thakkarnetram** [comment]
@gurshaan17 nope i already did that , sorry forgot to close !
