### ISSUE TITLE
API needed for User Profile /api/v1/profile

### ISSUE THREAD

**Issue by thakkarnetram** [thakkarnetram/BeProductiveBackend#20]
This API will be used to show the user's data 
-Name [ user cannot update ]
-User Name [ user can update ] 
-Email  [ user cannot update ] 
-Password  [ user can update ] 
In order to update the password we will use the Reset Routes which already exists , the user has to provide an email and then they will receive Password Reset Link on their Email

**Comment by wasiuddinmansoori1** [comment]
assign to me

**Comment by savitakatwe** [comment]
@thakkarnetram I can work on this assign it to me

**Comment by thakkarnetram** [comment]
Assigned @savitakatwe

**Comment by savitakatwe** [comment]
@thakkarnetram I am not able to do this work kinda stuck with other work.
